name: raspberry-pi-build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  raspberry-pi-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Secrets
        run: |
          cd src
          echo "#define STRAVA_SECRET_KEY ${{ secrets.strava_secret_key }}" > secret.h
          echo "#define SMTP_USERNAME ${{ secrets.smtp_username }}" >> secret.h
          echo "#define SMTP_PASSWORD ${{ secrets.smtp_password }}" >> secret.h
          echo "#define SMTP_SERVER ${{ secrets.smtp_server }}" >> secret.h
          echo "${{ secrets.cesiumkey }}" >> inner_templates/googlemaps/cesium-key.js
          echo "#define LICENSE" >> secret.h
          cd ..

      - name: Build for Raspberry Pi
        uses: docker://arm32v7/debian:buster
        with:
          args: >
            bash -c "
            set -ex &&
            apt-get update && 
            apt-get install -y build-essential git cmake qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qtquickcontrols2-5-dev libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 libqt5networkauth5-dev libqt5websockets5-dev qt5-default libqt5texttospeech5-dev libqt5location5 libqt5multimedia5-dev &&
            export QT_SELECT=qt5 &&
            export PATH=/usr/lib/qt5/bin:$PATH &&
            cd /github/workspace &&
            sed -i '/QtHttpServer/d' qdomyos-zwift.pro &&
            find src -type f \( -name '*.cpp' -o -name '*.h' \) -exec sed -i 's/#include <QtHttpServer/\/\/#include <QtHttpServer/' {} + &&
            find src -type f \( -name '*.cpp' -o -name '*.h' \) -exec sed -i 's/QHttpServer/\/\/QHttpServer/' {} + &&
            cat qdomyos-zwift.pro &&
            qmake &&
            make -j$(nproc)
            "

      - name: Archive Raspberry Pi binary
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-binary
          path: src/qdomyos-zwift