# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: '${{ github.workspace }}/output/linux-desktop/' 
          # An explicit key for restoring and saving the cache
          key: qt-linux-desktop

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          host: 'linux'
          target: 'desktop'
          modules: 'qtcharts debug_info'
          dir: '${{ github.workspace }}/output/linux-desktop/'
      
      - name: Compile
        run: cd src; qmake; make -j4
        
      - name: Archive linux-desktop binary
        uses: actions/upload-artifact@v2
        with:
          name: linux-desktop-binary
          path: src/qdomyos-zwift
