name: raspberry-pi-build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  raspberry-pi-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodule repo (SmtpClient-for-Qt)
        uses: actions/checkout@v2
        with:
          repository: bluetiger9/SmtpClient-for-Qt
          path: "src/smtpclient/"
          ref: 3fa4a0fe5797070339422cf18b5e9ed8dcb91f9c

      - name: Checkout submodule repo (qmdnsengine)
        uses: actions/checkout@v2
        with:
          repository: cagnulein/qmdnsengine
          path: "src/qmdnsengine/"
          ref: "zwift"

      - name: Checkout submodule repo (googletest)
        uses: actions/checkout@v2
        with:
          repository: google/googletest
          path: "tst/googletest/"
          ref: "release-1.12.1"

      - name: Checkout qHttpServer
        uses: actions/checkout@v2
        with:
          repository: qt-labs/qthttpserver
          path: "src/qthttpserver"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build for Raspberry Pi
        uses: docker://balenalib/raspberry-pi-debian:buster
        with:
          args: >
            bash -c "
            apt-get update && 
            apt-get install -y build-essential git cmake qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qtquickcontrols2-5-dev libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 libqt5networkauth5-dev libqt5websockets5* &&
            cd /github/workspace &&
            cp qHttpServerBin/5.15.2/headers/* src/qthttpserver/src/3rdparty/http-parser/ &&
            cd src/qthttpserver &&
            qmake &&
            make -j$(nproc) &&
            make install &&
            cd ../.. &&
            qmake &&
            make -j$(nproc)
            "

      - name: Archive Raspberry Pi binary
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-binary
          path: src/qdomyos-zwift