# This is a basic workflow to help you get started with Actions

name: CI

env:
  DISPLAY: ':99'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master,  github-workflow-playground, local-runner ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */12 * * *"    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Compile Linux Desktop
        run: |
            cd ../../; rm src/secret.h; git reset --hard; git pull
            echo "#define STRAVA_SECRET_KEY ${{ secrets.strava_secret_key }}" > src/secret.h
            echo "#define SMTP_USERNAME ${{ secrets.smtp_username }}" >> src/secret.h 
            echo "#define SMTP_PASSWORD ${{ secrets.smtp_password }}" >> src/secret.h 
            echo "#define SMTP_SERVER ${{ secrets.smtp_server }}" >> src/secret.h 
            "/Users/cagnulein/Qt/5.15.0/android/bin/qmake" src/qdomyos-zwift.pro -spec android-clang CONFIG-=qtquickcompiler 'ANDROID_ABIS=armeabi-v7a arm64-v8a x86 x86_64'
            "/Users/cagnulein/Library/Android/sdk/ndk/21.1.6352462/prebuilt/darwin-x86_64/bin/make" -f build-qdomyos-zwift-Android_Qt_5_15_0_android_Clang_Multi_Abi-Release/Makefile qmake_all
            "/Users/cagnulein/Library/Android/sdk/ndk/21.1.6352462/prebuilt/darwin-x86_64/bin/make" -j8
            "/Users/cagnulein/Library/Android/sdk/ndk/21.1.6352462/prebuilt/darwin-x86_64/bin/make" INSTALL_ROOT=build-qdomyos-zwift-Android_Qt_5_15_0_android_Clang_Multi_Abi-Release/android-build install
            "/Users/cagnulein/Qt/5.15.0/android/bin/androiddeployqt" --input build-qdomyos-zwift-Android_Qt_5_15_0_android_Clang_Multi_Abi-Release/android-qdomyos-zwift-deployment-settings.json --output build-qdomyos-zwift-Android_Qt_5_15_0_android_Clang_Multi_Abi-Release/android-build --android-platform android-31 --jdk /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home --gradle --sign '${{secrets.android_certificate_password}}' --storepass '${{secrets.android_certificate_password}}'
