name: raspberry-pi-build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  raspberry-pi-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Secrets
        run: |
          cd src
          echo "#define STRAVA_SECRET_KEY ${{ secrets.strava_secret_key }}" > secret.h
          echo "#define SMTP_USERNAME ${{ secrets.smtp_username }}" >> secret.h
          echo "#define SMTP_PASSWORD ${{ secrets.smtp_password }}" >> secret.h
          echo "#define SMTP_SERVER ${{ secrets.smtp_server }}" >> secret.h
          echo "${{ secrets.cesiumkey }}" >> inner_templates/googlemaps/cesium-key.js
          echo "#define LICENSE" >> secret.h
          cd ..

      - name: Build for Raspberry Pi
        uses: docker://balenalib/raspberry-pi-debian:buster
        with:
          args: >
            bash -c "
            set -x &&
            apt-get update && 
            apt-get install -y build-essential git cmake qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qtquickcontrols2-5-dev libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 libqt5networkauth5-dev libqt5websockets5-dev qt5-default &&
            export QT_SELECT=qt5 &&
            export PATH=/usr/lib/qt5/bin:$PATH &&
            cd /github/workspace &&
            cp qHttpServerBin/5.15.2/headers/* src/qthttpserver/src/3rdparty/http-parser/ &&
            cd src/qthttpserver &&
            find . -type f -name '*.pro' -exec sed -i 's/websockets-private/websockets/g' {} + &&
            find . -type f -name '*.h' -exec sed -i 's/include <private\/qwebsocket/include <QWebSocket/g' {} + &&
            find . -type f -name '*.cpp' -exec sed -i 's/include <private\/qwebsocket/include <QWebSocket/g' {} + &&
            sed -i 's/#include <private\/qobject_p.h>/#include <QObject>/g' src/httpserver/qabstracthttpserver_p.h &&
            sed -i 's/i->lastHeader.compare(/i->lastHeader.compare(QByteArray(/g' src/httpserver/qhttpserverrequest.cpp &&
            sed -i 's/INCLUDEPATH += $$PWD/INCLUDEPATH += $$PWD \/usr\/include\/arm-linux-gnueabihf\/qt5\/QtCore\/5.11.3\/QtCore\/private/g' src/httpserver/httpserver.pro &&
            cat src/httpserver/httpserver.pro &&
            qmake &&
            make -j$(nproc) &&
            make install &&
            cd ../.. &&
            sed -i 's/websockets-private/websockets/g' qdomyos-zwift.pro &&
            cat qdomyos-zwift.pro &&
            qmake &&
            make -j$(nproc)
            "

      - name: Archive Raspberry Pi binary
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-binary
          path: src/qdomyos-zwift