name: openSBOM
on: push
jobs: 
  open_SBOM:
    runs-on: ubuntu-latest
  
    steps:
    # checkout branch
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Generate SBOM #syft SBOM generation
        uses: opensbom-generator/spdx-sbom-generator@v0
        with:
          format: spdx-json
          artifact-name: artifactopensbom.json
          output-file: "opensbom.json"

      - name: View SBOM #syft
        run: cat "opensbom.json"
      
